/// Persistent energy source data types, registry, and emission system.
///
/// This module defines the data model for grid energy sources — persistent
/// emitters that inject heat or chemical values into field write buffers
/// each tick during the WARM emission phase.

use crate::grid::world_init::SourceFieldConfig;
use crate::grid::Grid;
use rand::Rng;
use smallvec::SmallVec;

/// Identifies which grid field a source emits into.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SourceField {
    Heat,
    Chemical(usize),
}

/// Opaque identifier for a registered source.
///
/// Internally a generational index: the `generation` field detects stale
/// removals after a slot has been reused, preventing the ABA problem.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct SourceId {
    pub(crate) index: usize,
    pub(crate) generation: u64,
}

/// A persistent emitter that injects a value into a grid field each tick.
///
/// Plain data struct — no methods beyond construction. Negative `emission_rate`
/// values are valid and represent drains (sinks).
///
/// Renewable sources use `f32::INFINITY` for `reservoir` and `initial_capacity`.
/// This eliminates branching in the emission loop — the deceleration math works
/// identically for both renewable and finite sources.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct Source {
    pub cell_index: usize,
    pub field: SourceField,
    /// Base emission rate (units per tick). May be negative for sinks.
    pub emission_rate: f32,
    /// Remaining emittable quantity. `f32::INFINITY` for renewable sources.
    pub reservoir: f32,
    /// Total capacity at creation. `f32::INFINITY` for renewable sources.
    /// Used as denominator in deceleration computation.
    pub initial_capacity: f32,
    /// Fraction of initial_capacity below which emission decelerates.
    /// 0.0 = no deceleration (full rate until exhaustion).
    /// 1.0 = deceleration begins immediately.
    pub deceleration_threshold: f32,
}

/// Internal slot in the `SourceRegistry`. Holds an optional source and a
/// generation counter for generational index validation.
pub(crate) struct SourceSlot {
    pub(crate) source: Option<Source>,
    pub(crate) generation: u64,
}

/// Errors from source registration and management.
#[derive(Debug, Clone, PartialEq, thiserror::Error)]
pub enum SourceError {
    #[error("cell index {cell_index} out of bounds (grid has {cell_count} cells)")]
    CellOutOfBounds {
        cell_index: usize,
        cell_count: usize,
    },

    #[error("chemical species {species} out of range (grid has {num_chemicals} species)")]
    InvalidChemicalSpecies {
        species: usize,
        num_chemicals: usize,
    },

    #[error("invalid source id (index={index}, generation={generation})")]
    InvalidSourceId {
        index: usize,
        generation: u64,
    },

    #[error("invalid reservoir: finite source requires reservoir > 0.0 and reservoir <= initial_capacity, got reservoir={reservoir}, initial_capacity={initial_capacity}")]
    InvalidReservoir {
        reservoir: f32,
        initial_capacity: f32,
    },

    #[error("deceleration threshold {threshold} out of range [0.0, 1.0]")]
    InvalidDecelerationThreshold {
        threshold: f32,
    },
}

/// Depletion event emitted when a non-renewable source's reservoir hits zero.
///
/// Generated by `run_emission` on the first tick a finite source's reservoir
/// transitions from positive to zero. Renewable sources (infinite reservoir)
/// never produce depletion events.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct DepletionEvent {
    /// The generational id of the depleted source.
    pub source_id: SourceId,
    /// Which field type the source was emitting into.
    pub field: SourceField,
    /// The tick on which depletion occurred.
    pub tick: u64,
}

/// Stores all active sources in a contiguous Vec with generational slots.
///
/// Slot-based storage: each slot holds an `Option<Source>` and a generation
/// counter. Removed slots become `None` and are reused on the next insert.
/// A free list tracks available slots to avoid linear scans on insertion.
pub struct SourceRegistry {
    slots: Vec<SourceSlot>,
    free_list: Vec<usize>,
    active_count: usize,
}

impl SourceRegistry {
    /// Create an empty registry.
    pub fn new() -> Self {
        Self {
            slots: Vec::new(),
            free_list: Vec::new(),
            active_count: 0,
        }
    }

    /// Add a source. Returns a `SourceId` for later removal.
    ///
    /// Validates `cell_index` against `cell_count` and chemical species
    /// against `num_chemicals`. Reuses free slots via the free list.
    pub fn add(
        &mut self,
        source: Source,
        cell_count: usize,
        num_chemicals: usize,
    ) -> Result<SourceId, SourceError> {
        // Validate cell bounds.
        if source.cell_index >= cell_count {
            return Err(SourceError::CellOutOfBounds {
                cell_index: source.cell_index,
                cell_count,
            });
        }

        // Validate chemical species if applicable.
        if let SourceField::Chemical(species) = source.field {
            if species >= num_chemicals {
                return Err(SourceError::InvalidChemicalSpecies {
                    species,
                    num_chemicals,
                });
            }
        }

        // Validate reservoir fields.
        // Renewable sources: both reservoir and initial_capacity must be INFINITY.
        // Finite sources: both must be finite, positive, and reservoir <= initial_capacity.
        let r = source.reservoir;
        let ic = source.initial_capacity;
        if r.is_infinite() && ic.is_infinite() {
            // Renewable — valid.
        } else if r.is_infinite() || ic.is_infinite() {
            // Mixed infinite/finite — invalid.
            return Err(SourceError::InvalidReservoir {
                reservoir: r,
                initial_capacity: ic,
            });
        } else {
            // Both finite: must be positive and reservoir <= initial_capacity.
            if r <= 0.0 || r.is_nan() || ic <= 0.0 || ic.is_nan() || r > ic {
                return Err(SourceError::InvalidReservoir {
                    reservoir: r,
                    initial_capacity: ic,
                });
            }
        }

        // Validate deceleration threshold in [0.0, 1.0].
        let t = source.deceleration_threshold;
        if !(0.0..=1.0).contains(&t) {
            return Err(SourceError::InvalidDecelerationThreshold { threshold: t });
        }

        let (index, generation) = if let Some(free_index) = self.free_list.pop() {
            // Reuse a freed slot. Generation was already bumped on removal.
            let slot = &mut self.slots[free_index];
            slot.source = Some(source);
            (free_index, slot.generation)
        } else {
            // Append a new slot.
            let index = self.slots.len();
            self.slots.push(SourceSlot {
                source: Some(source),
                generation: 0,
            });
            (index, 0)
        };

        self.active_count += 1;

        Ok(SourceId { index, generation })
    }

    /// Remove a source by its identifier.
    ///
    /// Returns `SourceError::InvalidSourceId` if the id is stale or out of range.
    pub fn remove(&mut self, id: SourceId) -> Result<(), SourceError> {
        let slot = self.slots.get_mut(id.index).ok_or(SourceError::InvalidSourceId {
            index: id.index,
            generation: id.generation,
        })?;

        if slot.generation != id.generation || slot.source.is_none() {
            return Err(SourceError::InvalidSourceId {
                index: id.index,
                generation: id.generation,
            });
        }

        slot.source = None;
        slot.generation += 1;
        self.free_list.push(id.index);
        self.active_count -= 1;

        Ok(())
    }

    /// Number of active (non-removed) sources.
    pub fn len(&self) -> usize {
        self.active_count
    }

    /// Whether the registry has no active sources.
    pub fn is_empty(&self) -> bool {
        self.active_count == 0
    }

    /// Iterate active sources in deterministic slot order.
    pub fn iter(&self) -> impl Iterator<Item = &Source> {
        self.slots.iter().filter_map(|slot| slot.source.as_ref())
    }

    /// Mutable iteration over active sources in deterministic slot order.
    /// Required by `run_emission` to mutate reservoir state during depletion.
    pub fn iter_mut(&mut self) -> impl Iterator<Item = &mut Source> {
        self.slots
            .iter_mut()
            .filter_map(|slot| slot.source.as_mut())
    }

    /// Mutable iteration yielding `(SourceId, &mut Source)` pairs in
    /// deterministic slot order. Required by `run_emission` for depletion
    /// tracking — the `SourceId` is needed to record which source depleted.
    pub fn iter_mut_with_ids(&mut self) -> impl Iterator<Item = (SourceId, &mut Source)> {
        self.slots
            .iter_mut()
            .enumerate()
            .filter_map(|(index, slot)| {
                let generation = slot.generation;
                slot.source
                    .as_mut()
                    .map(|source| (SourceId { index, generation }, source))
            })
    }

    /// Returns true if the source identified by `id` exists and is depleted
    /// (reservoir == 0.0). Renewable sources (reservoir = INFINITY) are never
    /// depleted.
    pub fn is_depleted(&self, id: SourceId) -> Result<bool, SourceError> {
        let slot = self.slots.get(id.index).ok_or(SourceError::InvalidSourceId {
            index: id.index,
            generation: id.generation,
        })?;

        if slot.generation != id.generation || slot.source.is_none() {
            return Err(SourceError::InvalidSourceId {
                index: id.index,
                generation: id.generation,
            });
        }

        // SAFETY of unwrap: guarded by the is_none() check above.
        let source = slot.source.as_ref().expect("checked above");
        Ok(source.reservoir == 0.0)
    }

    /// Count of active sources with reservoir > 0.0 (includes renewable
    /// sources where reservoir is INFINITY). Depleted sources (reservoir == 0.0)
    /// are excluded.
    pub fn active_emitting_count(&self) -> usize {
        self.slots
            .iter()
            .filter_map(|slot| slot.source.as_ref())
            .filter(|source| source.reservoir > 0.0)
            .count()
    }
}

// WARM PATH: Executes once per tick over the source list.
// No heap allocation. No dynamic dispatch. Sequential iteration.

/// Inject emission rates from all active sources into the appropriate
/// field write buffers, draining reservoirs for non-renewable sources.
///
/// Iterates the registry in deterministic slot order. For each source:
/// - Skips depleted sources (reservoir == 0.0, but not INFINITY).
/// - Computes effective emission rate with deceleration when reservoir
///   falls below `deceleration_threshold * initial_capacity`.
/// - Clamps actual emission to remaining reservoir.
/// - Subtracts actual emission from reservoir.
///
/// Renewable sources (reservoir = INFINITY) emit at full rate every tick
/// with no reservoir mutation (INFINITY - R = INFINITY).
///
/// Returns depletion events for non-renewable sources whose reservoir
/// transitioned from positive to zero on this tick. Renewable sources
/// never produce depletion events.
///
/// Caller is responsible for copy-read-to-write before calling this,
/// and for validation + swap after.
pub fn run_emission(
    grid: &mut Grid,
    registry: &mut SourceRegistry,
    current_tick: u64,
) -> SmallVec<[DepletionEvent; 8]> {
    let mut depletions = SmallVec::new();

    for (source_id, source) in registry.iter_mut_with_ids() {
        // Skip depleted non-renewable sources.
        // f32::INFINITY > 0.0 is true, so renewable sources pass this check.
        if source.reservoir == 0.0 {
            continue;
        }

        // Snapshot reservoir before drain to detect the positive→zero transition.
        let was_positive = source.reservoir > 0.0 && source.reservoir.is_finite();

        let threshold_capacity = source.deceleration_threshold * source.initial_capacity;

        // Compute effective emission rate with deceleration.
        // When reservoir is INFINITY, the first branch always fires (∞ > any finite).
        // When threshold is 0.0, threshold_capacity is 0.0, so reservoir > 0.0 >= 0.0
        // also takes the first branch (full rate until exhaustion).
        let effective_rate = if source.deceleration_threshold == 0.0
            || source.reservoir > threshold_capacity
        {
            source.emission_rate
        } else {
            // Linear deceleration: rate scales with remaining fraction of threshold band.
            source.emission_rate * (source.reservoir / threshold_capacity)
        };

        // Clamp to remaining reservoir. For renewable sources (INFINITY),
        // min(effective_rate, INFINITY) = effective_rate, so no clamping occurs.
        let actual_emission = if source.reservoir.is_infinite() {
            effective_rate
        } else {
            effective_rate.min(source.reservoir)
        };

        // Drain reservoir. INFINITY - finite = INFINITY, so renewable sources
        // are unaffected.
        source.reservoir -= actual_emission;

        // Clamp reservoir to zero to avoid floating-point undershoot.
        // Also snap to zero when the reservoir is so small that emission
        // has become negligible — the deceleration formula creates Zeno's
        // paradox where reservoir asymptotically approaches zero without
        // reaching it. Without this snap, sources become effectively inert
        // but never trigger depletion events. The 1e-4 threshold means
        // the source is emitting less than 0.01% of a unit per tick —
        // indistinguishable from zero in the simulation.
        if source.reservoir < 0.0 || (source.reservoir > 0.0 && actual_emission < 1e-4) {
            source.reservoir = 0.0;
        }

        // Detect depletion: reservoir was positive and finite, now zero.
        // Renewable sources (infinite reservoir) never trigger this.
        if was_positive && source.reservoir == 0.0 {
            depletions.push(DepletionEvent {
                source_id,
                field: source.field,
                tick: current_tick,
            });
        }

        // Write to the appropriate field buffer.
        match source.field {
            SourceField::Heat => {
                grid.write_heat()[source.cell_index] += actual_emission;
            }
            SourceField::Chemical(species) => {
                // Species validated at add() time. Defensive get avoids
                // panic if registry and grid are somehow out of sync.
                if let Ok(buf) = grid.write_chemical(species) {
                    buf[source.cell_index] += actual_emission;
                }
            }
        }
    }

    depletions
}


// ── Respawn queue data structures ──────────────────────────────

/// A pending source respawn. Stored in the `RespawnQueue`.
///
/// Plain data struct — no methods. Created when a non-renewable source
/// depletes and `respawn_enabled` is true for its field type.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct RespawnEntry {
    /// Which field type to respawn (Heat or Chemical(species)).
    pub field: SourceField,
    /// The tick at which the replacement source should spawn.
    pub respawn_tick: u64,
}

/// Pre-allocated queue of pending source respawns.
///
/// Stored on `Grid`. Iterated once per tick during the WARM respawn phase.
/// The queue is bounded by total source count — memory footprint is trivial.
///
/// `drain_mature` returns entries in deterministic order: by `respawn_tick`
/// ascending, then by insertion order for ties (stable sort).
pub struct RespawnQueue {
    entries: Vec<RespawnEntry>,
}

impl RespawnQueue {
    /// Create an empty queue with pre-allocated capacity.
    pub fn with_capacity(cap: usize) -> Self {
        Self {
            entries: Vec::with_capacity(cap),
        }
    }

    /// Add a pending respawn entry.
    pub fn push(&mut self, entry: RespawnEntry) {
        self.entries.push(entry);
    }

    /// Number of pending entries.
    pub fn len(&self) -> usize {
        self.entries.len()
    }

    /// Whether the queue is empty.
    pub fn is_empty(&self) -> bool {
        self.entries.is_empty()
    }

    /// Drain all entries whose `respawn_tick <= current_tick`.
    ///
    /// Returns mature entries in deterministic order: sorted by `respawn_tick`
    /// ascending, with insertion-order stability for ties.
    /// Entries not yet mature remain in the queue in their original order.
    ///
    /// WARM path — called once per tick, queue is small (bounded by source count).
    /// The `Vec` allocation here is acceptable for a WARM-frequency operation.
    pub fn drain_mature(&mut self, current_tick: u64) -> Vec<RespawnEntry> {
        // Partition: mature entries first, immature entries retained.
        let mut mature = Vec::new();
        let mut retained = Vec::new();

        for entry in self.entries.drain(..) {
            if entry.respawn_tick <= current_tick {
                mature.push(entry);
            } else {
                retained.push(entry);
            }
        }

        self.entries = retained;

        // Stable sort by respawn_tick preserves insertion order for ties.
        mature.sort_by_key(|e| e.respawn_tick);

        mature
    }
}


/// WARM PATH: Process mature respawn entries and spawn replacement sources.
///
/// Called after emission, before actor phases. For each mature entry:
/// 1. Sample source parameters from the corresponding `SourceFieldConfig`.
/// 2. Pick a random cell not occupied by an active source of the same field type.
/// 3. Register the new source in the `SourceRegistry`.
///
/// If all cells are occupied for a given field type, the entry is re-queued
/// with `respawn_tick += 1` (retry next tick).
///
/// Replacement sources are always non-renewable (`renewable_prob = 0.0`),
/// maintaining the depletion→cooldown→respawn loop.
pub fn run_respawn_phase(
    grid: &mut Grid,
    rng: &mut impl Rng,
    current_tick: u64,
    heat_config: &SourceFieldConfig,
    chemical_config: &SourceFieldConfig,
    _num_chemicals: usize,
) {
    // Drain mature entries from the queue. This detaches them so we can
    // mutate the grid (add sources) without borrowing the queue.
    let mature = grid.respawn_queue_mut().drain_mature(current_tick);

    if mature.is_empty() {
        return;
    }

    let cell_count = grid.cell_count();

    for entry in mature {
        let config = match entry.field {
            SourceField::Heat => heat_config,
            SourceField::Chemical(_) => chemical_config,
        };

        // Collect occupied cell indices for this field type.
        // WARM frequency, small set — allocation acceptable.
        let occupied: std::collections::HashSet<usize> = grid
            .sources()
            .iter()
            .filter(|s| s.field == entry.field)
            .map(|s| s.cell_index)
            .collect();

        if occupied.len() >= cell_count {
            // All cells occupied — defer to next tick.
            grid.respawn_queue_mut().push(RespawnEntry {
                field: entry.field,
                respawn_tick: entry.respawn_tick + 1,
            });
            continue;
        }

        // Select a random unoccupied cell. For sparse grids (typical case),
        // random sampling terminates in 1–2 attempts. For dense grids
        // (occupancy > 50%), build a vec of unoccupied indices and sample
        // uniformly from it.
        let cell_index = if occupied.len() * 2 > cell_count {
            // Dense: build unoccupied list and sample.
            let unoccupied: Vec<usize> = (0..cell_count)
                .filter(|i| !occupied.contains(i))
                .collect();
            // unoccupied is non-empty because we checked occupied.len() < cell_count above.
            unoccupied[rng.random_range(0..unoccupied.len())]
        } else {
            // Sparse: rejection-sample random indices.
            loop {
                let candidate = rng.random_range(0..cell_count);
                if !occupied.contains(&candidate) {
                    break candidate;
                }
            }
        };

        // Sample source parameters — always non-renewable (renewable_prob = 0.0).
        let emission_rate =
            rng.random_range(config.min_emission_rate..=config.max_emission_rate);
        let capacity =
            rng.random_range(config.min_reservoir_capacity..=config.max_reservoir_capacity);
        let deceleration_threshold =
            rng.random_range(config.min_deceleration_threshold..=config.max_deceleration_threshold);

        let source = Source {
            cell_index,
            field: entry.field,
            emission_rate,
            reservoir: capacity,
            initial_capacity: capacity,
            deceleration_threshold,
        };

        // Register the new source. add_source validates cell bounds and species,
        // which should always pass given our cell_index and field are derived
        // from valid grid state. Log and discard on error (defensive).
        if let Err(_e) = grid.add_source(source) {
            // Defensive: should not happen with valid cell selection and field type.
            // In a production build with tracing, this would be a warning log.
            continue;
        }
    }
}

